name=NeoPixelEffects
version=1.0.0
author=Joshua
maintainer=Joshua
sentence=Libreria modular para matrices NeoPixel RGB 8x8.
paragraph=Incluye efectos RGB, Snake, DAC I2C, utilidades de color y control modular de matrices LED.
category=Display
url=https://github.com/salinaszarcojoshua-max/code-proyect/tree/main/src
architectures=*
includes=NeoPixelEffects.h